local p = require("highlights.palette")

return {
	Normal         = {fg = p.ubuna_fg, bg = p.ubuna_bg},
	Keyword        = {fg = p.ubuna_fg, bold = false},
	Function       = {fg = p.ubuna_fg},
	StorageClass   = {fg = p.ubuna_fg, bold = false},
	Define         = {fg = p.ubuna_fg, bold = false},
	Structure      = {fg = p.ubuna_fg, bold = false},
	Typedef        = {fg = p.ubuna_fg},
	Type           = {fg = p.ubuna_fg},
	Tag            = {fg = p.ubuna_fg},
	Macro          = {fg = p.ubuna_fg},
	PreCondit      = {fg = p.ubuna_fg},
	Label          = {fg = p.ubuna_fg},
	Statement      = {fg = p.ubuna_fg},
	Conditional    = {fg = p.ubuna_fg, bold = false},
	Operator       = {fg = p.ubuna_fg},
	Repeat         = {fg = p.ubuna_fg},
	Identifier     = {fg = p.ubuna_fg},
	Number         = {fg = p.ubuna_fg},
	Constant       = {fg = p.ubuna_fg},
	String         = {fg = p.ubuna_green},
	Special        = {fg = p.ubuna_fg},
	SpecialChar    = {fg = p.ubuna_fg},
	SpecialKey     = {fg = p.ubuna_fg},
	Delimiter      = {fg = p.ubuna_fg},
	Directory      = {fg = p.ubuna_fg},
	Search         = {fg = p.ubuna_fg, bg = p.ubuna_bg_light},
	Fold           = {fg = p.ubuna_fg, bg = p.ubuna_bg},
	FoldColumn     = {fg = p.ubuna_fg, bg = p.ubuna_bg},
	CursorLineFold = {fg = p.ubuna_fg, bg = p.ubuna_bg},
	VisualNOS      = {fg = p.ubuna_fg, bg = p.ubuna_bg_light},
	MatchParen     = {bg = p.ubuna_niagara},

	TabLine        = {fg = p.ubuna_fg, bg = p.ubuna_none},
	TabLineFill    = {fg = p.ubuna_fg, bg = p.ubuna_none},
	TabLineSel     = {fg = p.ubuna_fg, bg = p.ubuna_none},

	Comment        = {fg = p.ubuna_fg1},
	SpecialComment = {fg = p.ubuna_fg},
	Debug          = {fg = p.ubuna_fg},
	PreProc        = {fg = p.ubuna_fg},
	LineNr         = {fg = p.ubuna_fg1},
	SignColumn     = {bg = p.ubuna_bg},
	CursorLineNr   = {fg = p.ubuna_bg},
	Statusline     = {bg = p.ubuna_bg_dark},
	StatusLineNC   = {fg = p.ubuna_bg_dark, bg = p.ubuna_bg_dark},
	Visual         = {bg = p.ubuna_bg_dark},
	EndOfBuffer    = {fg = p.ubuna_bg_light},
	NonText        = {fg = p.ubuna_bg_light},
	Pmenu          = {fg = p.ubuna_fg, bg = p.ubuna_bg_dark},
	PmenuSel       = {bg = p.ubuna_bg_light},
	WildMenu       = {fg = p.ubuna_fg, bg = p.ubuna_bg},
	Title          = {fg = p.ubuna_fg, bg = p.ubuna_none},
	FloatTitle     = {fg = p.ubuna_fg, bg = p.ubuna_none},
	Conceal        = {fg = p.ubuna_fg, bg = p.ubuna_bg_light},
	Cursor         = {fg = p.ubuna_fg, bg = p.ubuna_bg_light},
	Boolean        = {fg = p.ubuna_fg},
	Character      = {fg = p.ubuna_fg},
	Float          = {fg = p.ubuna_fg},
	Include        = {fg = p.ubuna_fg},
}
